<img alt="Colaboratory logo" width="15%" src="https://raw.githubusercontent.com/carlosfab/escola-data-science/master/img/novo_logo_bg_claro.png">

#### **Data Science na Prática 4.0**


---

# PREVISÃO DE DEMANDA

Como falamos antes, nossos templates ficarão cada vez mais simples!!

O objetivo desse projeto é prever a demanda por vinhos em lojas especializadas em vinho. Para esse projeto, temos 2 datasets, um sobre o catálogo de vinhos da loja e outro sobre as vendas.

* [Dados sobre os produtos](https://raw.githubusercontent.com/rafaelnduarte/sigmoidal_data/master/products.csv)
* [Dados de Vendas](https://raw.githubusercontent.com/rafaelnduarte/sigmoidal_data/master/sales-clean.csv)

Nesse projeto, é VITAL que haja MUITA ATENÇÃO sobre os detalhes mencionados que permeiam as análise de séries temporais. É um projeto que demanda muita atenção e cuidado, e uma documentação feita minuciosamente.

Aqui, queremos, como sempre, trazer o máximo de autonomia e independência pra vocês. Façam o download, e disponibilizem os seus dados, carreguem eles aqui, e desenvolvam o projeto.

## Objetivos

* Contextualização do problema, dos dados, do projeto.
* Análise completa dos dados e do problema (Na mão, ou com Pandas Profiling, SweetViz, etc)
* Desenvolver uma solução de Machine Learning eficiente com Prophet para Regressão

LEMBREM-SE: Documentação, Storytelling, Artigo com Código!

Mãos à obra e boa sorte!

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [2]:
dados_produtos = "https://raw.githubusercontent.com/rafaelnduarte/sigmoidal_data/master/products.csv"
dados_vendas = "https://raw.githubusercontent.com/rafaelnduarte/sigmoidal_data/master/sales-clean.csv"

In [4]:
df_produtos = pd.read_csv(dados_produtos)
df_produtos.head()

,item_id,name,producer,country,region,vintage,kind,price_brl,price_usd
0,1,Philipponnat Royale Reserve Brut,Philipponat,France,Champagne,NV,sparkling,339.60,58.75
1,2,Philipponnat Royale Reserve Rosé,Philipponat,France,Champagne,NV,rose sparkling,489.00,84.60
2,3,Philipponnat Cuvée 1522 Grand Cru Extra Brut,Philipponat,France,Champagne,2009,sparkling,789.00,136.51
3,4,Philipponnat Cuvée 1522 1er Cru Rosé,Philipponat,France,Champagne,2008,rose sparkling,899.40,155.61
4,5,Philipponnat Clos Des Goisses Brut,Philipponat,France,Champagne,2009,sparkling,"1,548.00",267.82

In [6]:
df_produtos.shape

(219, 9)

In [5]:
df_vendas = pd.read_csv(dados_vendas)
df_vendas.head()

         date  store  item  sales
0  2018-01-01      1     1     13
1  2018-01-02      1     1     11
2  2018-01-03      1     1     14
3  2018-01-04      1     1     13
4  2018-01-05      1     1     10

In [8]:
df_vendas.shape

(720071, 4)

In [ ]:
sns.plot